# Generated by Django 5.0.2 on 2024-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSourceUsersEnriched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update_time', models.CharField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, null=True)),
                ('source_user_id', models.CharField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, null=True)),
                ('jobtitle', models.CharField(blank=True, null=True)),
                ('programming_languages', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('source', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, null=True)),
                ('experience_months', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_source_users_enriched',
                'managed': False,
            },
        ),
    ]
