# Generated by Django 5.0.2 on 2024-04-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_allsourceusersenriched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsourceusersenriched',
            options={'managed': True},
        ),
    ]
