# Generated by Django 5.0.2 on 2024-04-13 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_allsourceusersenriched_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsourceusersenriched',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, null=True), default='no data', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allsourceusersenriched',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allsourceusersenriched',
            name='programming_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), default='no data', size=None),
            preserve_default=False,
        ),
    ]
