# Generated by Django 5.0.2 on 2024-04-13 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_allsourceusersenriched_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsourceusersenriched',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=0, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='allsourceusersenriched',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
